note:
  version: 1
  name: Enamine US Oct 2023 + Rxn115
  description: |
    Enamine Rush Delivery Building Blocks (US) Oct 2023, initially used in ChemProjector model.
    Rxn115 (115 reactions) template set.
    The batch size is set to 512 for smaller GPU memory requirements.

remote:
  chemical_space_url: https://huggingface.co/datasets/luost26/prexsyn-data/resolve/main/chemical_spaces/enamine2310_rxn115.chemspace

chemical_space:
  cache_path: data/chemical_spaces/enamine2310_rxn115.chemspace
  bb_path: data/building_blocks/Enamine_Rush-Delivery_Building_Blocks-US_223244cmpd_20231001.sdf
  rxn_path: data/reactions/rxn115.txt
  building_block_selectivity_cutoff: 8 # No cutoff in the original implementation

descriptors:
  - type: ecfp4
    num_embedding_tokens: 4
  - type: fcfp4
    num_embedding_tokens: 4

featurizer:
  max_length: 16

model:
  dim: 1024
  nhead: 16
  dim_feedforward: 2048
  num_layers: 12
  bb_embed_dim: 1024

training:
  batch_size: 512
  val_freq: 2000
  seed: 2026
  data_pipeline_num_cpus: 15
  val_seed: 2026
  num_val_batches: 10
  loss_weights:
    token_types: 1.0
    bb_indices: 1.0
    rxn_indices: 1.0
  optimizer:
    lr: 3.e-4
  scheduler:
    T_max: 500
    eta_min: 1.e-5
