chemical_space:
  cache_path: data/chemical_spaces/enamine2310_rxn115.chemspace
  remote_url:
  bb_path: data/building_blocks/Enamine_Rush-Delivery_Building_Blocks-US_223244cmpd_20231001.sdf
  rxn_path: data/reactions/rxn115.txt
  building_block_selectivity_cutoff: 8 # No cutoff in the original implementation
descriptors:
  ecfp4:
    type: ecfp4
    num_embedding_tokens: 4
  fcfp4:
    type: fcfp4
    num_embedding_tokens: 4
featurizer:
  max_length: 16
model:
  dim: 1024
  nhead: 16
  dim_feedforward: 2048
  num_layers: 12
  bb_embed_dim: 1024
training:
  batch_size: 1024
